spring:
  application:
    name: RGT
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
    username: root
    url: jdbc:mysql://localhost:3306/rgt?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
        show_sql: 'false'
server:
  port: '8088'